apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kwetter-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kwetter-ingress
    networking.gke.io/managed-certificates: kwettercertificate
spec:
  rules:
  - http:
      paths:
      - path: /api/*
        backend:
          serviceName: kwetter-gateway-api
          servicePort: 8080
      - path: /*
        backend:
          serviceName: kwetter-frontend-service
          servicePort: 8080