apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: userapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: eu.gcr.io/kwetter-274507/userapi:latest
        ports:
        - containerPort: 7002
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m  